INSERT INTO department (department_name)
VALUES
  ('Research'),('Engineering'),('Marketing'),('Management');

INSERT INTO role (title,salary,department_id)
VALUES
  ('Research lead',120000, 1),
  ('Researcher',60000, 1),
  ('Business Intelligence',185000, 1),
  ('Software Engineer',115000, 2),
  ('Head of Engineering',105000, 2),
  ('Marketing Lead',75000, 3),
  ('Secretary',45000, 4),
  ('CEO',300000, 4);

INSERT INTO employee (first_name,last_name,role_id,manager_id)
VALUES
  ('Taylor', 'Swift', 1, NULL),
  ('Michael', 'Jackson', 2, 1),
  ('Lewandowski', 'Robert', 2, 1),
  ('Lionel', 'Messi', 3, NULL),
  ('Cristiano', 'Ronaldo', 4, 4),
  ('Pable', 'Escobar', 4, 4),
  ('Ali', 'Maqsood', 4, 4),
  ('Paolo', 'Maldini', 5, NULL),
  ('Paul', 'Scholes', 6, 8),
  ('Ricardo', 'Kaka', 7, NULL),
  ('Mo', 'Salah', 8, 10),
  ('Wayne', 'Rooney', 8, 10);

  INSERT INTO voters (first_name, last_name, email)
VALUES
  ('James', 'Fraser', 'jf@goldenbough.edu'),
  ('Jack', 'London', 'jlondon@ualaska.edu'),
  ('Robert', 'Bruce', 'rbruce@scotland.net'),
  ('Peter', 'Greenaway', 'pgreenaway@postmodern.com'),
  ('Derek', 'Jarman', 'djarman@prospectcottage.net'),
  ('Paolo', 'Pasolini', 'ppasolini@salo.com'),
  ('Heathcote', 'Williams', 'hwilliams@bafta.com'),
  ('Sandy', 'Powell', 'spowell@oscars.com'),
  ('Emil', 'Zola', 'ezola@requin.com'),
  ('Sissy', 'Coalpits', 'scoalpits@greenaway.com'),
  ('Antoinette', 'Capet', 'acapet@dontloseyourhead.com'),
  ('Samuel', 'Delany', 'sdelany@dhalgren.com'),
  ('Tony', 'Duvert', 'tduvert@frenchletters.edu'),
  ('Dennis', 'Cooper', 'dcooper@georgemiles.com'),
  ('Monica', 'Bellucci', 'mbell@irreverisble.net'),
  ('Samuel', 'Johnson', 'sjohnson@boswell.com'),
  ('John', 'Dryden', 'jdryden@restoration.net'),
  ('Alexander', 'Pope', 'apope@cambridge.uk.edu'),
  ('Lionel', 'Johnson', 'ljohnson@darkangel.com'),
  ('Aubrey', 'Beardsley', 'abeardsely@wilde.net'),
  ('Tulse', 'Luper', 'tluper@films.net'),
  ('William', 'Morris', 'wmorris@victoriana.com'),
  ('George', 'Shaw', 'gshaw@labor.uk'),
  ('Arnold', 'Bennett', 'abennett@poemsgalore.com'),
  ('Algernon', 'Blackwood', 'ablack@creepy.net'),
  ('Rhoda', 'Broughton', 'rb@feminist.com'),
  ('Hart', 'Crane', 'hcrane@schwesters.de'),
  ('Vitorio', 'DeSica', 'vdesica@italiano.net'),
  ('Wilkie', 'Collins', 'wcollins@madmonkton.com'),
  ('Elizabeth', 'Gaskell', 'egaskell@pages.net'),
  ('George', 'Sand', 'gsand@pride.com'),
  ('Vernon', 'Lee', 'vlee@spooks.net'),
  ('Arthur', 'Machen', 'amach@spirits.com'),
  ('Frederick', 'Marryat', 'fmarry@boats.net'),
  ('Harriet', 'Martineau', 'hmartineau@journalism.com'),
  ('George', 'Meredith', 'gm@egoist.uk'),
  ('Margaret', 'Oliphant', 'moli@victoriana.com'),
  ('Anthony', 'Trollope', 'atrollope@barchester.com'),
  ('Charlotte', 'Yonge', 'cyonge@newday.com'),
  ('Horace', 'Walpole', 'hwal@otranto.net'),
  ('Matthew', 'Lewis', 'mlewis@monk.com'),
  ('William', 'Bedford', 'wbed@grandtour.net'),
  ('Anne', 'Radcliffe', 'arad@udolpho.uk'),
  ('Charles', 'Brown', 'cbrown@wieland.us'),
  ('Eliza', 'Parsons', 'lizzie@fierce.net'),
  ('Susan', 'Hill', 'shill@womaninblack.net'),
  ('Sydney', 'Owenson', 'Sowen@think.net'),
  ('Hubert', 'Crackanthorpe', 'hcrackan@goodletters.com'),
  ('William', 'Carleton', 'wcarleton@literature.com'),
  ('Gerald', 'Griffin', 'ggriff@lit.net');